# Generated by Django 4.1.2 on 2023-05-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
